#!/bin/sh
if [ $# -ne 3 ]
  then
      read -s -p "`echo 'Enter svc_pvzcards password: \n\b'`"  svc_pw
      read -s -p "`echo 'Enter login keychain password (probably your network password): \n\b'`"  keychain_pw
      read -s -p "`echo 'Enter password for signing certificates: \n\b'`"  cert_pw
  else 
      svc_pw=$1
      keychain_pw=$2
      cert_pw=$3
fi

if ! command -v p4 >/dev/null; then
    source ~/.bash_profile
    if ! command -v p4 >/dev/null; then
        echo "p4 not in path; aborting"
        exit 1
    fi
fi

echo "$svc_pw" | p4 -u svc_pvzcards login > /dev/null
if [ $? -ne 0 ]
then
    echo "Bad password for svc_pvzcards"
    exit
fi
p4 -u svc_pvzcards -c pvzcards_certs sync -f //... > /dev/null
pushd /pvzcards_certs > /dev/null

#install provisions
mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
for file in *.mobileprovision; do
    uuid=`grep UUID -A1 -a "$file" | grep -io "[-A-Z0-9]\{36\}"`
    extension="${file##*.}"
    cp -f "$file" ~/Library/MobileDevice/Provisioning\ Profiles/"$uuid.$extension"
done

#install certs
security unlock-keychain -p $keychain_pw login.keychain
for file in *.p12; do
    security import $file -A -k login.keychain -P $cert_pw > /dev/null
done
security lock-keychain login.keychain

popd > /dev/null
p4 -u svc_pvzcards -c pvzcards_certs sync -f //...@0 > /dev/null
p4 -u svc_pvzcards logout > /dev/null
