#!/bin/sh
if [ $# -ne 2 ]
  then
      read -s -p "`echo 'Enter svc_pvzcards password: \n\b'`"  svc_pw
      read -s -p "`echo 'Enter login keychain password (probably your network password): \n\b'`"  pw
  else 
      svc_pw=$1
      pw=$2
fi

if ! command -v p4 >/dev/null; then
    source ~/.bash_profile
    if ! command -v p4 >/dev/null; then
        echo "p4 not in path; aborting"
        exit 1
    fi
fi

echo "$svc_pw" | p4 -u svc_pvzcards login > /dev/null
if [ $? -ne 0 ]
then
    echo "Bad password for svc_pvzcards"
    exit
fi
p4 -u svc_pvzcards -c pvzcards_certs sync -f //... > /dev/null
pushd /pvzcards_certs > /dev/null

#install provisions
mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
for file in *.*provision*; do
    uuid=`grep UUID -A1 -a "$file" | grep -io "[-A-Z0-9]\{36\}"`
    extension="${file##*.}"
    cp -f "$file" ~/Library/MobileDevice/Provisioning\ Profiles/"$uuid.$extension"
done

#install certs
security unlock-keychain -p $pw login.keychain
security import ./ROW_Development.p12 -A -k login.keychain -P jamdat1 > /dev/null
security import ./iOS_Dev_Certificates.p12 -A -k login.keychain -P WWGFD > /dev/null
security lock-keychain login.keychain

popd > /dev/null
p4 -u svc_pvzcards -c pvzcards_certs sync -f //...@0 > /dev/null
rm -r /pvzcards_certs
p4 -u svc_pvzcards logout > /dev/null
